# Generated by Django 2.1 on 2018-08-26 10:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0002_auto_20180826_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
