# Generated by Django 2.1 on 2018-08-26 11:14

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0003_auto_20180826_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
