# Generated by Django 2.1 on 2018-08-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0006_auto_20180827_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(default=0),
        ),
    ]
