# Generated by Django 2.1.1 on 2018-08-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0007_auto_20180830_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(default='All', max_length=8),
            preserve_default=False,
        ),
    ]
