# Generated by Django 2.1.1 on 2018-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0008_job_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='external_link',
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('A', 'All'), ('M', 'Male'), ('F', 'Female')], max_length=8),
        ),
    ]
