# Generated by Django 2.1.1 on 2018-09-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0009_auto_20180906_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='owner',
            new_name='user',
        ),
    ]
