# Generated by Django 2.1.1 on 2018-09-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0011_auto_20180910_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female')], max_length=8),
        ),
    ]
