# Generated by Django 2.1.1 on 2018-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0012_auto_20180910_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female')], default='All', max_length=8),
        ),
    ]
