# Generated by Django 2.1.1 on 2018-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0013_auto_20180910_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='Python Developer', max_length=50),
            preserve_default=False,
        ),
    ]
