# Generated by Django 2.1.1 on 2018-09-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0015_auto_20180911_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AddField(
            model_name='type',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
