# Generated by Django 2.1.1 on 2018-09-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0016_auto_20180914_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='abbreviation',
        ),
    ]
