# Generated by Django 2.1.1 on 2018-09-26 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0019_auto_20180926_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
