# Generated by Django 2.1.1 on 2018-09-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakujobs', '0020_auto_20180926_1001'),
        # ('employer', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Employer'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
